#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail

mkdir -p ~/.gitshots
LOG_FILE=~/.gitshots/log.txt
touch "$LOG_FILE"

SCRIPTS_DIR=~/.git-post-commit-scripts

for file in $SCRIPTS_DIR/* ; do
  if [[ -x $file ]]; then
    "$file" >>"$LOG_FILE" 2>&1
  fi
done
